/**
 * Portrait Feature — Interface Contract
 * ======================================
 * Single source of truth for all four worktrees.
 * Changes require explicit sign-off and must be communicated to all agents.
 *
 * Worktree-1 (portrait-data):    schema, OAuth, sync, enrichment, import
 * Worktree-2 (portrait-generation): LLM portrait prose, themes, bookshelf OCR
 * Worktree-3 (portrait-ui):      all Portrait tab components, empty states
 * Worktree-4 (portrait-interactions): animations, popovers, modals, filters
 */

// =============================================================================
// 1. DATABASE TABLES
// =============================================================================

/**
 * spotify_profiles — one row per user, upserted on each sync
 * PK is user_id (not a separate id column).
 */
export interface SpotifyProfile {
  user_id: string;                // UUID, PK, FK → profiles.id
  synced_at: string;              // timestamptz — last successful sync
  is_active: boolean;             // false = disconnected (soft delete)

  // Tokens — encrypted at rest, never exposed to client
  spotify_access_token: string;
  spotify_refresh_token: string;

  // Aggregates computed server-side during sync
  top_artists: SpotifyArtist[];   // jsonb — top 10
  top_genres: GenreCount[];       // jsonb — mapped vocabulary
  avg_valence: number;            // 0–1
  avg_energy: number;             // 0–1
  avg_tempo: number;              // BPM
  pct_minor: number;              // 0–1
  avg_acousticness: number;       // 0–1
  listening_mode: 'immersion' | 'explorer';
  cultural_geography: RegionCount[]; // jsonb

  // Mood — derived from valence/energy quadrant, no LLM needed
  mood_label: 'Euphoric' | 'Peaceful' | 'Intense' | 'Melancholic';
  mood_line: string;              // e.g. "minor key · contemplative · slow"

  // Portrait prose — generated by Claude Haiku
  portrait_text: string | null;
  portrait_generated_at: string | null;
  last_portrait_manual_at: string | null; // for 7-day throttle
}

export interface SpotifyArtist {
  name: string;
  image_url: string | null;
  genres: string[];               // raw Spotify genre strings
}

export interface GenreCount {
  genre: string;                  // mapped label from spotify-genre-map.json
  count: number;
}

export interface RegionCount {
  region: string;
  count: number;
}

/**
 * books — one row per book per user.
 * NEW TABLE. Populated from card entries, reviews, bookshelf import, Goodreads CSV.
 * Separate from reviews table — a book can exist without a review.
 */
export interface Book {
  id: string;                     // UUID, PK
  user_id: string;                // UUID, FK → profiles.id
  title: string;                  // NOT NULL
  author: string | null;

  // Google Books enrichment
  cover_url: string | null;       // cached from Google Books
  google_books_id: string | null;
  google_books_genres: string[] | null; // jsonb
  google_books_description: string | null;

  // Goodreads enrichment (from CSV import)
  goodreads_genres: string[] | null; // jsonb

  // Status & source
  status: 'reading' | 'read' | 'want_to_read';
  source: 'card' | 'review' | 'bookshelf_import' | 'goodreads_csv';

  // Rating — synced from reviews table (0–10 scale, matching existing reviews)
  rating: number | null;
  review_id: string | null;       // UUID, FK → reviews.id, nullable

  created_at: string;
}

/**
 * experiences — past cultural events displayed in Portrait.
 * Separate from the activities table (which tracks upcoming events on the Activity Board).
 */
export interface Experience {
  id: string;                     // UUID, PK
  user_id: string;                // UUID, FK → profiles.id
  name: string;                   // NOT NULL
  category: ExperienceCategory;
  date: string | null;            // date (not timestamptz)
  city: string | null;
  note: string | null;
  source: 'activity_board' | 'manual';
  created_at: string;
}

export type ExperienceCategory =
  | 'concert'
  | 'exhibition'
  | 'restaurant'
  | 'cinema'
  | 'theatre'
  | 'other';

/**
 * creations — user-authored original work (poems, screenshots, photos, writing).
 */
export interface Creation {
  id: string;                     // UUID, PK
  user_id: string;                // UUID, FK → profiles.id
  type: 'text' | 'image';
  title: string | null;           // max 80 chars
  text_content: string | null;    // max 2000 chars, for type="text"
  image_url: string | null;       // Supabase Storage URL, for type="image"
  is_visible: boolean;            // DEFAULT true — eye toggle
  created_at: string;
}

/**
 * profiles extension — columns added to the existing profiles table.
 */
export interface ProfilePortraitExtension {
  reading_themes: string[] | null;  // jsonb — ["memory & loss", "post-colonial voices", ...]
  reading_themes_at: string | null; // timestamptz — last theme generation
}


// =============================================================================
// 2. RATING SCALE MAPPING
// =============================================================================

/**
 * Existing reviews table uses 0–10 scale.
 * PRD weighting logic uses 5-star language. Mapping:
 *
 *   0–10 range  | PRD equivalent | Signal weight
 *   -----------|----------------|--------------------------------------
 *   8–10        | 4–5★ (high)    | Primary signal — always included
 *   5–7         | 3★ (mid)       | Deprioritized (no review) or included (with review)
 *   1–4         | 1–2★ (low)     | Excluded without review, included with review
 *   0 or null   | Unrated        | Deprioritized
 */
export const RATING_HIGH_MIN = 8;
export const RATING_MID_MIN = 5;
export const RATING_LOW_MIN = 1;

/**
 * Signal weighting for portrait generation (worktree-2 uses this logic):
 *
 *   Status            | Rating    | Has review? | Weight
 *   ------------------|-----------|-------------|----------------------------
 *   read              | 8–10      | yes         | PRIMARY — always included
 *   read              | 8–10      | no          | PRIMARY — clean positive signal
 *   read              | 1–4       | yes         | INCLUDED — review explains it
 *   read              | 5–7       | yes         | INCLUDED
 *   read              | 5–7       | no          | DEPRIORITIZED
 *   read              | 1–4       | no          | EXCLUDED — ambiguous
 *   read              | unrated   | no          | DEPRIORITIZED
 *   reading           | n/a       | n/a         | CONTEXT — "currently reading"
 *   bookshelf_import  | unrated   | n/a         | BACKGROUND — context only
 */


// =============================================================================
// 3. MOOD CLASSIFICATION (no LLM — derived from Spotify aggregates)
// =============================================================================

export const MOOD_QUADRANTS = {
  Euphoric:    { valence: '> 0.6', energy: '> 0.6' },
  Peaceful:    { valence: '> 0.6', energy: '<= 0.6' },
  Intense:     { valence: '<= 0.6', energy: '> 0.6' },
  Melancholic: { valence: '<= 0.6', energy: '<= 0.6' },
} as const;

export type MoodLabel = keyof typeof MOOD_QUADRANTS;


// =============================================================================
// 4. EDGE FUNCTION SIGNATURES
// =============================================================================

/**
 * POST /functions/v1/spotify-auth
 * Handles OAuth 2.0 with PKCE for Spotify connection.
 */
export interface SpotifyAuthRequest {
  action: 'connect' | 'callback' | 'disconnect';
  // connect: returns redirect_url
  // callback: receives code + code_verifier, exchanges for tokens
  // disconnect: sets is_active = false
  code?: string;
  code_verifier?: string;
}

export interface SpotifyAuthResponse {
  success: boolean;
  redirect_url?: string;         // for action=connect
  error?: string;
}

/**
 * POST /functions/v1/spotify-sync
 * Fetches top artists, top tracks, audio features from Spotify.
 * Computes aggregates. Atomically upserts spotify_profiles.
 * Called on initial connect + every 30 days via cron.
 */
export interface SpotifySyncRequest {
  user_id: string;               // target user (cron passes this; client omits it)
}

export interface SpotifySyncResponse {
  success: boolean;
  synced_at?: string;
  error?: string;
}

/**
 * POST /functions/v1/portrait-generate
 * Reads spotify_profiles + weighted books, calls Claude Haiku,
 * validates output (80–400 chars), stores in spotify_profiles.portrait_text.
 * One retry on failure; retains previous value if retry fails.
 */
export interface PortraitGenerateRequest {
  user_id: string;
  manual?: boolean;              // if true, checks 7-day throttle
}

export interface PortraitGenerateResponse {
  success: boolean;
  portrait_text?: string;
  mood_label?: MoodLabel;
  mood_line?: string;
  error?: string;
}

/**
 * POST /functions/v1/reading-themes
 * Reads primary-signal books, calls Claude Haiku, validates JSON array
 * of 2–5 strings (each <40 chars), stores in profiles.reading_themes.
 * Triggered at 3 books, then every 3 new books (3, 6, 9…).
 */
export interface ReadingThemesRequest {
  user_id: string;
}

export interface ReadingThemesResponse {
  success: boolean;
  themes?: string[];             // 2–5 theme strings
  error?: string;
}

/**
 * POST /functions/v1/bookshelf-scan
 * Receives a bookshelf photo, sends to Gemini Flash Vision API,
 * returns extracted titles and authors.
 * Rate limit: max 3 attempts per user per 24 hours.
 */
export interface BookshelfScanRequest {
  image_base64: string;          // base64-encoded photo
}

export interface BookshelfScanResponse {
  success: boolean;
  books?: { title: string; author: string | null }[];
  error?: string;
}

/**
 * POST /functions/v1/book-enrich
 * Given title + author, fetches cover, genres, description from Google Books API.
 * Used after card save, review submit, bookshelf import, and Goodreads CSV import.
 */
export interface BookEnrichRequest {
  title: string;
  author?: string;
}

export interface BookEnrichResponse {
  success: boolean;
  cover_url?: string;
  genres?: string[];
  description?: string;
  google_books_id?: string;
  error?: string;
}

/**
 * POST /functions/v1/goodreads-import
 * Receives CSV content, parses rows where Exclusive Shelf = "read",
 * enriches each via Google Books, upserts into books table.
 * Duplicate detection: title + author match → skip.
 * CSV is never stored server-side.
 */
export interface GoodreadsImportRequest {
  csv_content: string;           // raw CSV text
}

export interface GoodreadsImportResponse {
  success: boolean;
  imported_count: number;
  skipped_count: number;
  error?: string;
}


// =============================================================================
// 5. STATIC DATA FILES
// =============================================================================

/**
 * /data/spotify-genre-map.json
 * Maps raw Spotify genre strings to readable labels.
 *
 * Rules:
 * - Preserve culturally specific genres: "rap français", "afrobeats", "bossa nova"
 * - Clean up technical labels: "permanent wave" → "indie / rock"
 * - Discard obscure tags with no cultural meaning
 * - Built from real user data, not speculation
 *
 * Shape: Record<string, string | null>
 *   key: raw Spotify genre string
 *   value: mapped label, or null to discard
 */
export type SpotifyGenreMap = Record<string, string | null>;


// =============================================================================
// 6. EXPERIENCE CATEGORIES (shared constant)
// =============================================================================

export const EXPERIENCE_CATEGORIES: { value: ExperienceCategory; label: string }[] = [
  { value: 'concert',    label: 'Concert' },
  { value: 'exhibition', label: 'Exhibition' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'cinema',     label: 'Cinema' },
  { value: 'theatre',    label: 'Theatre' },
  { value: 'other',      label: 'Other' },
];


// =============================================================================
// 7. REFRESH SCHEDULE (for reference — worktree-2 implements)
// =============================================================================

/**
 * Content          | Trigger                               | Cadence
 * -----------------|---------------------------------------|------------------
 * Portrait prose   | Spotify sync completes                | Every 30 days
 * Mood label+line  | Spotify sync completes                | Every 30 days
 * Cultural geo     | Spotify sync completes                | Every 30 days
 * Reading themes   | Every 3rd primary-signal book added   | Rolling
 * Manual refresh   | User-initiated (Settings)             | Max once/7 days
 *
 * All LLM output validated:
 *   portrait_text: 80–400 chars
 *   reading_themes: JSON array of 2–5 strings, each <40 chars
 * One retry on failure; retain previous stored value if retry fails.
 */


// =============================================================================
// 8. SUPABASE STORAGE BUCKETS
// =============================================================================

/**
 * creation-images — stores uploaded creation images.
 * Path pattern: {user_id}/{creation_id}.{ext}
 * Max upload: 10MB, compressed to <2MB before storage (client-side).
 * Public read for visible items; RLS on the creations table controls visibility.
 */
export const CREATION_IMAGES_BUCKET = 'creation-images';


// =============================================================================
// 9. PORTRAIT LLM PROMPTS (worktree-2 implements — defined here for alignment)
// =============================================================================

/**
 * Portrait generation system prompt:
 *
 *   You are writing a cultural taste portrait for a private social app called Le Salon.
 *   Tone: warm, perceptive, slightly literary — like a thoughtful friend who notices things.
 *   Never use the word "data". Never list statistics. Write in second person. Max 3 sentences.
 *
 * Portrait generation user prompt template:
 *
 *   Mood: {mood_label}
 *   Music — top genres: {top_3_genres}
 *   Music — top artists: {top_5_artists}
 *   Music — % minor key: {pct_minor}, avg tempo: {avg_tempo} BPM,
 *            acousticness: {avg_acousticness}, mode: {listening_mode}
 *   Music — cultural geography: {cultural_geography}
 *   Reading — primary signal books (8-10 rated or reviewed): {primary_books}
 *   Reading — context books (currently reading, background): {context_books}
 *
 *   Write a portrait capturing the emotional and aesthetic texture of this person's
 *   cultural life. Find the thread connecting music and reading if one exists.
 *   Never mention numbers.
 *
 * Theme generation user prompt:
 *
 *   Given these books (all rated 8-10 or reviewed): {primary_books_with_descriptions}
 *
 *   Identify 3–4 recurring thematic preoccupations. Not genre labels — actual themes.
 *   Good examples: "memory & loss", "post-colonial voices", "slow fiction",
 *   "female interiority", "political violence", "the absurd".
 *
 *   Return only a JSON array of strings, no preamble.
 */
