-- Portrait Feature: Spotify profiles + tokens
-- See docs/portrait-interface-contract.ts for column shapes and Edge Function signatures.
--
-- Security note: tokens are stored in a SEPARATE table (spotify_tokens) with no
-- client-facing RLS policies. Only Edge Functions (service_role) can read/write tokens.
-- This is a deliberate improvement over the PRD's single-table design.

-- ---------------------------------------------------------------------------
-- spotify_tokens — OAuth tokens, service_role access only
-- ---------------------------------------------------------------------------
CREATE TABLE spotify_tokens (
  user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE spotify_tokens ENABLE ROW LEVEL SECURITY;
-- No RLS policies = no client access. Edge Functions use service_role key to bypass RLS.

-- ---------------------------------------------------------------------------
-- spotify_profiles — aggregates, mood, portrait prose (visible to owner + friends)
-- ---------------------------------------------------------------------------
CREATE TABLE spotify_profiles (
  user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  synced_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,

  -- Aggregates computed server-side during sync
  top_artists JSONB DEFAULT '[]'::jsonb,       -- [{name, image_url, genres[]}]
  top_genres JSONB DEFAULT '[]'::jsonb,         -- [{genre, count}] mapped vocabulary
  avg_valence FLOAT,                            -- 0–1
  avg_energy FLOAT,                             -- 0–1
  avg_tempo FLOAT,                              -- BPM
  pct_minor FLOAT,                              -- 0–1
  avg_acousticness FLOAT,                       -- 0–1
  listening_mode TEXT CHECK (listening_mode IN ('immersion', 'explorer')),
  cultural_geography JSONB DEFAULT '[]'::jsonb, -- [{region, count}]

  -- Mood classification — derived from valence/energy quadrant, no LLM needed
  mood_label TEXT CHECK (mood_label IN ('Euphoric', 'Peaceful', 'Intense', 'Melancholic')),
  mood_line TEXT,                                -- "minor key · contemplative · slow"

  -- Portrait prose — generated by Claude Haiku, served from cache
  portrait_text TEXT,
  portrait_generated_at TIMESTAMPTZ,
  last_portrait_manual_at TIMESTAMPTZ           -- for 7-day manual refresh throttle
);

-- Indexes
CREATE INDEX idx_spotify_profiles_active ON spotify_profiles(is_active) WHERE is_active = TRUE;

-- Enable RLS
ALTER TABLE spotify_profiles ENABLE ROW LEVEL SECURITY;

-- Owner: full access
CREATE POLICY "Owner can view own Spotify profile"
  ON spotify_profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Owner can insert own Spotify profile"
  ON spotify_profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owner can update own Spotify profile"
  ON spotify_profiles FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Owner can delete own Spotify profile"
  ON spotify_profiles FOR DELETE
  USING (auth.uid() = user_id);

-- Friends: read-only
CREATE POLICY "Friends can view Spotify profiles"
  ON spotify_profiles FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM friendships
      WHERE status = 'accepted'
        AND ((requester_id = auth.uid() AND recipient_id = spotify_profiles.user_id)
             OR (recipient_id = auth.uid() AND requester_id = spotify_profiles.user_id))
    )
  );
