-- Portrait Feature: Books table
-- See docs/portrait-interface-contract.ts for column shapes.
--
-- NEW TABLE — no existing books table in the schema.
-- Populated from: weekly Card entries, Reviews, bookshelf photo import, Goodreads CSV.
-- A book can exist without a review (e.g. bookshelf import, card entry).

CREATE TABLE books (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  author TEXT,

  -- Google Books enrichment (fetched via book-enrich Edge Function)
  cover_url TEXT,
  google_books_id TEXT,
  google_books_genres JSONB,          -- ["Fiction", "Literary Fiction", ...]
  google_books_description TEXT,

  -- Goodreads enrichment (from CSV import only)
  goodreads_genres JSONB,             -- ["Fiction", "Classics", ...]

  -- Status & source
  status TEXT NOT NULL DEFAULT 'reading'
    CHECK (status IN ('reading', 'read', 'want_to_read')),
  source TEXT NOT NULL
    CHECK (source IN ('card', 'review', 'bookshelf_import', 'goodreads_csv')),

  -- Rating — synced from reviews table (0–10 scale, matching existing reviews)
  -- See interface contract §2 for rating-to-signal-weight mapping.
  rating NUMERIC CHECK (rating IS NULL OR (rating >= 0 AND rating <= 10)),
  review_id UUID REFERENCES reviews(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Duplicate detection: one book per title+author per user.
-- Used by Goodreads CSV import and bookshelf import to skip existing books.
-- lower() + coalesce() for case-insensitive, null-safe matching.
CREATE UNIQUE INDEX idx_books_user_title_author
  ON books(user_id, lower(title), lower(coalesce(author, '')));

-- Common query patterns
CREATE INDEX idx_books_user_status ON books(user_id, status);
CREATE INDEX idx_books_user_created ON books(user_id, created_at DESC);
CREATE INDEX idx_books_review ON books(review_id) WHERE review_id IS NOT NULL;

-- Enable RLS
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Owner: full access
CREATE POLICY "Owner can view own books"
  ON books FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Owner can insert own books"
  ON books FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owner can update own books"
  ON books FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Owner can delete own books"
  ON books FOR DELETE
  USING (auth.uid() = user_id);

-- Friends: read-only (for viewing friend's Portrait reading section)
CREATE POLICY "Friends can view books"
  ON books FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM friendships
      WHERE status = 'accepted'
        AND ((requester_id = auth.uid() AND recipient_id = books.user_id)
             OR (recipient_id = auth.uid() AND requester_id = books.user_id))
    )
  );

-- ---------------------------------------------------------------------------
-- Profiles extension: reading themes (stored on profiles, generated by LLM)
-- ---------------------------------------------------------------------------
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS reading_themes JSONB;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS reading_themes_at TIMESTAMPTZ;
